In [1]:
import pandas as pd 
import numpy as np

In [4]:
data= pd.read_csv('C:\\Users\\priya\\OneDrive\\Desktop\\computer_vsiosion_project\\data_validation_project\\PAN_DATA.csv')

In [5]:
data.head(5)

    Name    Age   Salary         PAN              Email
0   Aman   25.0  50000.0  DKQJD2673D     aman@gmail.com
1  Rohit   -5.0  60000.0  oiN4zAZyDF             rohit@
2  Priya  130.0 -10000.0  YQABN3510Y     priya@mail.com
3   Neha   40.0      NaN  kgEMEx6BvY  neha123@gmail.com
4    NaN   22.0  70000.0  LDYSG3590C                NaN

In [6]:
validated_data = pd.read_csv('C:\\Users\\priya\\OneDrive\\Desktop\\computer_vsiosion_project\\validated_data.csv')

In [7]:
validated_data.head(5)

,Name,Age,Salary,PAN,Email,PAN_valid,Email_valid,Age_valid,Salary_valid,Overall_Status,Errors
0,Aman,25.0,50000.0,DKQJD2673D,aman@gmail.com,True,True,True,True,True,NaN
1,Rohit,-5.0,60000.0,oiN4zAZyDF,rohit@,False,False,False,True,False,"Invalid PAN, Invalid Email, Invalid Age"
2,Priya,130.0,-10000.0,YQABN3510Y,priya@mail.com,True,True,False,False,False,"Invalid Age, Invalid Salary"
3,Neha,40.0,NaN,kgEMEx6BvY,neha123@gmail.com,False,True,True,False,False,"Invalid PAN, Invalid Salary"
4,NaN,22.0,70000.0,LDYSG3590C,NaN,True,False,True,True,False,Invalid Email

In [8]:
invalid_data = pd.read_csv('C:\\Users\\priya\\OneDrive\\Desktop\\computer_vsiosion_project\\invalid_data.csv')

In [9]:
invalid_data.head(5)

,Unnamed: 0,Name,Age,Salary,PAN,Email,PAN_valid,Email_valid,Age_valid,Salary_valid,Overall_Status,Errors
0,0,NaN,130.0,NaN,PATED2424K,ppgcpo@gmail.com,True,True,False,False,False,"Invalid Age, Invalid Salary"
1,1,Rohit,82.0,-10000.0,RYGQW2263R,test@gmail,True,False,True,False,False,"Invalid Email, Invalid Salary"
2,2,Rohit,-5.0,-10000.0,FCSOK2712J,mdkgry@gmail.com,True,True,False,False,False,"Invalid Age, Invalid Salary"
3,3,Priya,130.0,NaN,78zYyYWvBE,abc@,False,False,False,False,False,"Invalid PAN, Invalid Email, Invalid Age, Inval..."
4,4,Rahul,130.0,NaN,LXQZW4807U,dwthym@gmail.com,True,True,False,False,False,"Invalid Age, Invalid Salary"